label=input("Enter the student's name: ")
course=input("Enter the course: ")
print("----------------------------------""\n")
print(" Name   :",label,"\n")
print(" Course :",course,"\n")
print("----------------------------------")